spring.application.name=bjmanchsb
#Core properties
imageSize=150
imageFormat=png

#Database
spring.datasource.url=jdbc:mariadb://localhost:3306/bjm
spring.datasource.username=root
spring.datasource.password=Wether@lDr69
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers=true


spring.mail.host=smtp.livemail.co.uk
spring.mail.port=587
spring.mail.username=admin@bjmanch.org
spring.mail.password=Wether@lDr69
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#properties for email
webURI=localhost:8080
#webURI=https://www.bjmanch.org/
createAccessURI=createAccess.xhtml?email=%s
forumCreatedURI=forum/ForumDetails.xhtml?forumId=%s&amp;forumCreatorEmail=%s
surveyCreatedURI=survey/SurveyDetails.xhtml?surveyId=%s&amp;surveyCreatorEmail=%s
surveyCreatedFromForumURI=surveyFromForum/SurveyFromForumDetails.xhtml?surveyId=%s&amp;surveyCreatorEmail=%s
